### ISSUE TITLE
Discord sync error with Mythic v3

### ISSUE THREAD

**Issue by A-Lazar-A** [MythicC2Profiles/discord#5]
Could u help me with this problem?

```
ERROR 2024-09-16 16:54:55,099 syncC2ProfileData  421 : [-] Failed to sync discord: Error: Version, v1.3.3, isn't supported. The max supported version is v1.3.
```

**Comment by its-a-feature** [comment]
Sounds like Discord is using the latest Mythic PyPi package, but your Mythic server isn't the latest. What version of Mythic are you running?

**Comment by A-Lazar-A** [comment]
> Sounds like Discord is using the latest Mythic PyPi package, but your Mythic server isn't the latest. What version of Mythic are you running?
@its-a-feature 
[*] mythic-cli version:    v0.2.22
[*] Mythic Server version: v3.2.20-rc11
[*] React UI Version:      v0.1.86

**Comment by its-a-feature** [comment]
Yup, you're still on Mythic 3.2. https://github.com/MythicC2Profiles/discord/blob/main/C2_Profiles/discord/Dockerfile#L2 <-- right there, so `Mythic/InstalledServices/discord/Dockerfile` just add a line that says:
```
RUN pip3 install mythic-container==04.19
```
then `sudo ./mythic-cli build discord`. The container that Discord is using is always updated to the latest, but you're using an older version of Mythic, so this just forces your install to go back and use an older version as well

**Comment by its-a-feature** [comment]
I mean, I'd say yes, you should update the Mythic server instead (lots of new features/bug fixes), but I'm always cautious about updating something (especially for a 3.2 -> 3.3 update) mid-operation. So, if you don't have an active op, I'd say go for it. You'll need to update all of your other c2 profiles/agents as well (just reinstall them) to get their latest versions too

**Comment by A-Lazar-A** [comment]
Did 
`git pull`
`sudo make`
`sudo ./mythic-cli restart`
Got rabbitmq connection error
Did
`sudo ./mythic-cli build mythic_rabbitmq`
And now get this
```
2024/09/16 21:44:40 [-] Failed to make connection to host, retrying in 10s
2024/09/16 21:44:40 Get "https://127.0.0.1:7443/new/login": dial tcp 127.0.0.1:7443: connect: connection refused
2024/09/16 21:44:50 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443/new/login, attempt 4/10
2024/09/16 21:44:50 [-] Failed to make connection to host, retrying in 10s
2024/09/16 21:44:50 Get "https://127.0.0.1:7443/new/login": dial tcp 127.0.0.1:7443: connect: connection refused
```

Before that there are some logs of docker
```
2024/09/16 21:44:18 [*] Removing old volume, arachne_volume, if it exists
2024/09/16 21:44:18 [*] Removing old volume, thanatos_volume, if it exists
unknown flag: --build
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker context use")
```

**Comment by its-a-feature** [comment]
I means your Docker version is too outdated. Are you running on Kali linux by chance? The stand-alone `docker-compose` script wasn't getting updated and causing breaking issues for people, so I dropped support for that and require the `docker compose` plugin. It should be part of the newest Docker installs by default, otherwise you should be able to install the plugin. That's why the `--build` flag is unknown (and why it's showing `Usage: docker [OPTIONS]` instead of `Usage: docker compose [OPTIONS]`)

**Comment by A-Lazar-A** [comment]
Yep Im on kali
So im a bit confused about Docker because on 3.2 it worked fine
What should I do?

**Comment by its-a-feature** [comment]
It's because on 3.2 you weren't using `docker compose`, you were using `docker-compose` (one is a supported GO plugin for the Docker engine, the other is a python wrapper plugin that's not maintained or supported anymore). Since you updated to the latest Mythic, you should try giving the install_docker_kali script a shot to see if it installs the right version of Docker

**Comment by A-Lazar-A** [comment]
Thank you a lot!
By the way, is there any Agent that supports DNS profile?

**Comment by its-a-feature** [comment]
Not currently. It's on my list to add/update, but just haven't had the time yet
